import type { AutoPostTemplate } from "./types";

export const AUTO_POST_TEMPLATES_B: AutoPostTemplate[] = [
  {
    seedId: 3,
    title: "求兼职 咖啡店周末班",
    content:
      "江南站附近咖啡店招周末兼职，主要负责点单和简单清洁。韩语日常交流即可，时薪1万2左右，有意私信。",
    author: "留学生Lily",
    location: "江南站",
    distance: "800m",
    likes: 156,
    category: "招聘",
    nearby: true,
    topicKeywords: ["兼职", "咖啡店", "周末", "招聘", "江南"],
    allowedImageKeywords: ["coffee shop", "cafe", "barista", "coffee", "work"],
    forbiddenImageKeywords: ["bedroom", "landscape", "hiking", "dentist"],
    imageSearchQuery: "bright coffee shop barista natural light",
    imageCount: 1,
    curatedImages: [
      {
        url: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80",
        width: 800,
        height: 533,
        keyword: "coffee shop",
        source: "unsplash",
      },
      {
        url: "https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg?auto=compress&cs=tinysrgb&w=800",
        width: 800,
        height: 533,
        keyword: "cafe interior",
        source: "pexels",
      },
    ],
  },
  {
    seedId: 4,
    title: "出二手显示器 27寸2K",
    content:
      "自用27寸2K显示器转让，无坏点，带HDMI线。延寿区可自取，也可地铁面交，价格可小刀。",
    author: "数码达人",
    location: "延寿区",
    distance: "2.4km",
    likes: 89,
    category: "二手",
    nearby: true,
    topicKeywords: ["显示器", "二手", "27寸", "2K", "转让"],
    allowedImageKeywords: ["monitor", "computer screen", "display", "desk setup"],
    forbiddenImageKeywords: ["food", "landscape", "bedroom", "school", "running"],
    imageSearchQuery: "computer monitor desk bright office",
    imageCount: 2,
    curatedImages: [
      {
        url: "https://images.unsplash.com/photo-1527443225845-86d333776f7b?w=800&q=80",
        width: 800,
        height: 533,
        keyword: "computer monitor",
        source: "unsplash",
      },
      {
        url: "https://images.pexels.com/photos/777001/pexels-photo-777001.jpeg?auto=compress&cs=tinysrgb&w=800",
        width: 800,
        height: 533,
        keyword: "monitor display",
        source: "pexels",
      },
    ],
  },
  {
    seedId: 5,
    title: "韩国银行卡办理攻略",
    content:
      "刚到韩国办银行卡的经验分享：护照、ARC、在学证明备齐，推荐去明洞附近分行，英文服务较好。开户当天可领卡。",
    author: "首尔生活家",
    location: "明洞",
    distance: "3.8km",
    likes: 2156,
    category: "攻略",
    following: true,
    topicKeywords: ["银行卡", "办理", "攻略", "开户", "韩国"],
    allowedImageKeywords: ["bank card", "credit card", "banking", "wallet", "finance"],
    forbiddenImageKeywords: ["food", "landscape", "bedroom", "hiking"],
    imageSearchQuery: "bank card wallet bright lifestyle",
    imageCount: 1,
    curatedImages: [
      {
        url: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&q=80",
        width: 800,
        height: 533,
        keyword: "bank card",
        source: "unsplash",
      },
      {
        url: "https://images.pexels.com/photos/50987/money-card-business-credit-card-50987.jpeg?auto=compress&cs=tinysrgb&w=800",
        width: 800,
        height: 533,
        keyword: "credit card",
        source: "pexels",
      },
    ],
  },
  {
    seedId: 6,
    title: "明洞附近求租两室一厅",
    content:
      "想在明洞附近租两室一厅，预算适中，希望交通方便。有合适房源的朋友欢迎推荐，可长期租，安静整洁优先。",
    author: "小周找房",
    location: "明洞",
    distance: "350m",
    likes: 412,
    category: "房屋",
    nearby: true,
    topicKeywords: ["求租", "两室", "明洞", "租房", "房源"],
    allowedImageKeywords: ["apartment", "living room", "bedroom", "interior", "housing"],
    forbiddenImageKeywords: ["food", "landscape", "phone", "laptop"],
    imageSearchQuery: "apartment living room bright natural light",
    imageCount: 3,
    curatedImages: [
      {
        url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
        width: 800,
        height: 533,
        keyword: "living room",
        source: "unsplash",
      },
      {
        url: "https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg?auto=compress&cs=tinysrgb&w=800",
        width: 800,
        height: 533,
        keyword: "apartment interior",
        source: "pexels",
      },
    ],
  },
  {
    seedId: 7,
    title: "新村韩餐避雷指南",
    content:
      "新村几家网红韩餐实测：有的排队久但一般，有的隐藏小店反而惊喜。整理了口味、价位和踩雷点，帮大家少花冤枉钱。",
    author: "美食探店王",
    location: "新村",
    distance: "100m",
    likes: 892,
    category: "探店",
    nearby: true,
    following: true,
    topicKeywords: ["韩餐", "新村", "避雷", "探店", "美食"],
    allowedImageKeywords: ["korean food", "meal", "restaurant", "dining", "bibimbap"],
    forbiddenImageKeywords: ["apartment", "landscape", "monitor", "school"],
    imageSearchQuery: "korean food meal restaurant bright",
    imageCount: 2,
    curatedImages: [
      {
        url: "https://images.unsplash.com/photo-1498654896293-37aacf113fd9?w=800&q=80",
        width: 800,
        height: 533,
        keyword: "korean food",
        source: "unsplash",
      },
      {
        url: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=800",
        width: 800,
        height: 533,
        keyword: "healthy meal",
        source: "pexels",
      },
    ],
  },
  {
    seedId: 8,
    title: "急求帮搬行李 有偿",
    content:
      "刚到韩国行李较多，龙山站附近需要帮忙搬到楼上，有偿感谢。时间今天下午，有空的兄弟姐妹请联系。",
    author: "刚到韩国",
    location: "龙山站",
    distance: "800m",
    likes: 67,
    category: "求助",
    nearby: true,
    topicKeywords: ["搬行李", "求助", "有偿", "龙山"],
    allowedImageKeywords: ["moving", "luggage", "boxes", "suitcase", "help"],
    forbiddenImageKeywords: ["food", "landscape", "bbq", "school"],
    imageSearchQuery: "moving boxes luggage apartment bright",
    imageCount: 1,
    curatedImages: [
      {
        url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
        width: 800,
        height: 533,
        keyword: "moving boxes",
        source: "unsplash",
      },
      {
        url: "https://images.pexels.com/photos/424614/pexels-photo-424614.jpeg?auto=compress&cs=tinysrgb&w=800",
        width: 800,
        height: 533,
        keyword: "luggage suitcase",
        source: "pexels",
      },
    ],
  },
  {
    seedId: 9,
    title: "出让宜家书桌 几乎全新",
    content:
      "毕业出清宜家书桌，使用不到半年，几乎全新。水原站附近自取，可附赠台灯，价格好商量。",
    author: "毕业出清",
    location: "水原站",
    distance: "3.8km",
    likes: 203,
    category: "二手",
    topicKeywords: ["宜家", "书桌", "二手", "出让", "毕业"],
    allowedImageKeywords: ["desk", "study desk", "furniture", "workspace", "table"],
    forbiddenImageKeywords: ["food", "landscape", "running", "school building"],
    imageSearchQuery: "wooden desk workspace bright natural light",
    imageCount: 2,
    curatedImages: [
      {
        url: "https://images.unsplash.com/photo-1518459031867-a89b294d41d8?w=800&q=80",
        width: 800,
        height: 533,
        keyword: "study desk",
        source: "unsplash",
      },
      {
        url: "https://images.pexels.com/photos/1957478/pexels-photo-1957478.jpeg?auto=compress&cs=tinysrgb&w=800",
        width: 800,
        height: 533,
        keyword: "workspace desk",
        source: "pexels",
      },
    ],
  },
  {
    seedId: 10,
    title: "寻找周末 hiking 搭子",
    content:
      "高丽大附近寻找周末 hiking 搭子，路线难度中等，北汉山或近郊都可。希望有户外经验，一起拍照看风景。",
    author: "户外小陈",
    location: "高丽大",
    distance: "1.2km",
    likes: 534,
    category: "其他",
    nearby: true,
    following: true,
    topicKeywords: ["hiking", "搭子", "周末", "户外", "爬山"],
    allowedImageKeywords: ["hiking", "trail", "backpack", "outdoor", "trekking"],
    forbiddenImageKeywords: ["food", "bedroom", "monitor", "dentist"],
    imageSearchQuery: "people hiking trail bright sunny",
    imageCount: 2,
    curatedImages: [
      {
        url: "https://images.unsplash.com/photo-1551632811-561732d17410b?w=800&q=80",
        width: 800,
        height: 533,
        keyword: "hiking trail",
        source: "unsplash",
      },
      {
        url: "https://images.pexels.com/photos/1365425/pexels-photo-1365425.jpeg?auto=compress&cs=tinysrgb&w=800",
        width: 800,
        height: 533,
        keyword: "outdoor trekking",
        source: "pexels",
      },
    ],
  },
  {
    seedId: 11,
    title: "弘大附近短租一个月",
    content:
      "弘大附近短租一个月，家具齐全，拎包入住。近地铁，生活便利，适合短期交换或实习的同学。",
    author: "短期转租",
    location: "弘大",
    distance: "350m",
    likes: 278,
    category: "房屋",
    nearby: true,
    topicKeywords: ["短租", "弘大", "转租", "一个月", "租房"],
    allowedImageKeywords: ["apartment", "bedroom", "room", "interior", "housing"],
    forbiddenImageKeywords: ["food", "landscape", "phone", "running"],
    imageSearchQuery: "small apartment bedroom bright cozy",
    imageCount: 1,
    curatedImages: [
      {
        url: "https://images.pexels.com/photos/271743/pexels-photo-271743.jpeg?auto=compress&cs=tinysrgb&w=800",
        width: 800,
        height: 1067,
        keyword: "cozy bedroom",
        source: "pexels",
      },
      {
        url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80",
        width: 800,
        height: 533,
        keyword: "apartment room",
        source: "unsplash",
      },
    ],
  },
];
