import type { AutoPostTemplate } from "./types";

function pexels(
  id: number,
  keyword: string,
  width = 800,
  height: number = width === 800 ? 533 : 1067,
): AutoPostTemplate["curatedImages"][number] {
  return {
    url: `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=800`,
    width,
    height,
    keyword,
    source: "pexels",
  };
}

export const AUTO_POST_TEMPLATES_E: AutoPostTemplate[] = [
  {
    seedId: 31,
    title: "二手 iPad Pro 11寸成色新",
    content:
      "iPad Pro 11寸 2021款，256G，配原装笔和键盘壳。几乎全新，主要用于看网课，新村面交。",
    author: "平板出让",
    location: "新村",
    distance: "350m",
    likes: 421,
    category: "二手",
    nearby: true,
    topicKeywords: ["iPad", "Pro", "二手", "平板", "转让"],
    allowedImageKeywords: ["ipad", "tablet", "apple tablet", "notebook"],
    forbiddenImageKeywords: ["food", "landscape", "bedroom", "running"],
    imageSearchQuery: "ipad tablet desk bright",
    imageCount: 2,
    curatedImages: [pexels(133543, "ipad tablet"), pexels(18105, "apple laptop tablet")],
  },
  {
    seedId: 32,
    title: "汉江公园周末骑行搭子",
    content:
      "周末下午汉江公园休闲骑行，速度不快，适合新手。弘大出发，可共享自行车，求一起拍照的小伙伴。",
    author: "骑行爱好者",
    location: "弘大",
    distance: "800m",
    likes: 589,
    category: "其他",
    nearby: true,
    following: true,
    topicKeywords: ["骑行", "汉江", "搭子", "周末", "自行车"],
    allowedImageKeywords: ["cycling", "bicycle", "bike", "outdoor", "park"],
    forbiddenImageKeywords: ["food", "bedroom", "monitor", "dentist"],
    imageSearchQuery: "people cycling park bright sunny",
    imageCount: 2,
    curatedImages: [pexels(248547, "cycling bicycle"), pexels(2803158, "outdoor fitness")],
  },
  {
    seedId: 33,
    title: "弘大多久找房经验总结",
    content:
      "在弘大找房两周的总结：哪些区域性价比高、看房要检查什么、中介话术怎么避坑。附常见预算参考。",
    author: "弘大学姐",
    location: "弘大",
    distance: "350m",
    likes: 867,
    category: "攻略",
    following: true,
    topicKeywords: ["找房", "弘大", "经验", "攻略", "租房"],
    allowedImageKeywords: ["apartment", "bedroom", "room", "housing", "interior"],
    forbiddenImageKeywords: ["food", "landscape", "phone", "running"],
    imageSearchQuery: "student apartment room bright",
    imageCount: 2,
    curatedImages: [pexels(1571463, "student apartment"), pexels(271743, "cozy bedroom")],
  },
  {
    seedId: 34,
    title: "新村咖啡馆早班兼职",
    content:
      "新村地铁站附近咖啡馆招早班兼职，7点到12点，负责开店和简单餐点。时薪1.15万，能长期优先。",
    author: "咖啡店长",
    location: "新村",
    distance: "100m",
    likes: 143,
    category: "招聘",
    nearby: true,
    topicKeywords: ["早班", "咖啡馆", "兼职", "新村", "招聘"],
    allowedImageKeywords: ["coffee shop", "cafe", "barista", "coffee"],
    forbiddenImageKeywords: ["bedroom", "landscape", "hiking", "dentist"],
    imageSearchQuery: "bright coffee shop morning natural light",
    imageCount: 1,
    curatedImages: [pexels(302899, "coffee shop"), pexels(324028, "cafe barista")],
  },
  {
    seedId: 35,
    title: "仁川接机帮忙搬运行李",
    content:
      "周一下午仁川机场T1到达，行李较多，求有偿帮忙搬上车。目的地建大附近，有车的同学请联系。",
    author: "刚到首尔",
    location: "仁川机场",
    distance: "3.8km",
    likes: 76,
    category: "求助",
    nearby: true,
    topicKeywords: ["接机", "行李", "仁川", "求助", "搬运行李"],
    allowedImageKeywords: ["airport", "luggage", "travel", "terminal", "suitcase"],
    forbiddenImageKeywords: ["food", "bedroom", "bbq", "school"],
    imageSearchQuery: "airport luggage travelers bright",
    imageCount: 2,
    curatedImages: [pexels(912050, "airport travel"), pexels(424614, "luggage suitcase")],
  },
  {
    seedId: 36,
    title: "东大门清仓二手衣服",
    content:
      "东大门扫货买多啦，转让几件全新带吊牌外套和卫衣。均码为主，东大门面交，单件5千到2万不等。",
    author: "清仓小妹",
    location: "东大门",
    distance: "100m",
    likes: 198,
    category: "二手",
    nearby: true,
    topicKeywords: ["二手", "衣服", "东大门", "清仓", "转让"],
    allowedImageKeywords: ["clothes", "fashion", "clothing", "wardrobe", "apparel"],
    forbiddenImageKeywords: ["food", "landscape", "apartment", "laptop"],
    imageSearchQuery: "clothes fashion rack bright",
    imageCount: 2,
    curatedImages: [pexels(1926765, "clothes fashion"), pexels(996329, "clothing store")],
  },
  {
    seedId: 37,
    title: "梨泰院brunch探店",
    content:
      "梨泰院这家brunch颜值和口味都在线，班尼迪克蛋和松饼都推荐。周末建议预约，人均2-3万韩币。",
    author: "brunch女孩",
    location: "梨泰院",
    distance: "1.2km",
    likes: 743,
    category: "探店",
    nearby: true,
    following: true,
    topicKeywords: ["brunch", "梨泰院", "探店", "美食", "早餐"],
    allowedImageKeywords: ["brunch", "breakfast", "meal", "restaurant", "dining"],
    forbiddenImageKeywords: ["apartment", "landscape", "monitor", "school"],
    imageSearchQuery: "brunch breakfast restaurant bright",
    imageCount: 2,
    curatedImages: [pexels(1640777, "brunch meal"), pexels(725997, "restaurant dining")],
  },
  {
    seedId: 38,
    title: "留学生健康保险怎么选",
    content:
      "比较了国民健康保险和留学生保险的差异：报销比例、缴费方式、就医流程。刚到韩国建议先了解再选。",
    author: "留韩指南",
    location: "建大",
    distance: "2.4km",
    likes: 1124,
    category: "其他",
    following: true,
    topicKeywords: ["健康保险", "留学生", "保险", "就医", "韩国"],
    allowedImageKeywords: ["health insurance", "insurance", "healthcare", "medical", "clinic"],
    forbiddenImageKeywords: ["food", "landscape", "bedroom", "bbq"],
    imageSearchQuery: "health insurance healthcare bright",
    imageCount: 1,
    curatedImages: [pexels(4021779, "healthcare"), pexels(3845810, "medical clinic")],
  },
  {
    seedId: 39,
    title: "水原华城附近单间出租",
    content:
      "水原华城附近安静单间，适合在水原校区上课的同学。包网，月租友好，押一付一，可实地看房。",
    author: "水原房东",
    location: "水原",
    distance: "3.8km",
    likes: 267,
    category: "房屋",
    topicKeywords: ["单间", "水原", "华城", "出租", "租房"],
    allowedImageKeywords: ["bedroom", "room", "apartment", "interior", "housing"],
    forbiddenImageKeywords: ["food", "landscape", "phone", "running"],
    imageSearchQuery: "small bedroom apartment bright",
    imageCount: 2,
    curatedImages: [pexels(271743, "cozy bedroom"), pexels(1571460, "apartment bedroom")],
  },
  {
    seedId: 40,
    title: "新村部队锅哪家最稳",
    content:
      "新村几家部队锅对比：汤底咸度、料足程度、排队时间。这家老客户最多，加芝士和方便面绝配。",
    author: "部队锅Fans",
    location: "新村",
    distance: "100m",
    likes: 956,
    category: "探店",
    nearby: true,
    following: true,
    topicKeywords: ["部队锅", "新村", "探店", "美食", "韩餐"],
    allowedImageKeywords: ["hot pot", "korean food", "meal", "restaurant", "dining"],
    forbiddenImageKeywords: ["apartment", "landscape", "laptop", "school"],
    imageSearchQuery: "korean hot pot food restaurant bright",
    imageCount: 3,
    curatedImages: [
      pexels(1267320, "korean food"),
      pexels(1640777, "hot pot meal"),
      pexels(725997, "restaurant dining"),
    ],
  },
];
