import { pexelsPhoto } from "./pexels-url";
import type { AutoPostTemplate } from "./types";

/** Batch 3 (51–60): image-first Korea street / life / second-hand. */
export const AUTO_POST_TEMPLATES_G: AutoPostTemplate[] = [
  {
    seedId: 51,
    title: "弘大晚上霓虹灯就这样",
    content:
      "周五晚上在弘大随便逛，霓虹灯和人流就是照片里这种氛围。不购物也适合散步拍照，11点后店会关一批。",
    author: "夜逛选手",
    location: "弘大",
    distance: "350m",
    likes: 723,
    category: "攻略",
    nearby: true,
    following: true,
    imageFirst: true,
    requireImages: true,
    topicKeywords: ["弘大", "夜景", "霓虹", "逛街", "攻略"],
    allowedImageKeywords: ["seoul night", "neon", "street", "city night"],
    forbiddenImageKeywords: ["europe", "cathedral", "countryside"],
    imageSearchQuery: "seoul night street neon",
    imageCount: 2,
    curatedImages: [
      pexelsPhoto(5877412, "seoul night street"),
      pexelsPhoto(2087028, "seoul city night"),
    ],
  },
  {
    seedId: 52,
    title: "第一次看首尔夜景在这拍的",
    content:
      "来韩第一次专门去看城市夜景，就是这张照片的角度。风很大但值得，建议和室友一起去。",
    author: "初来首尔",
    location: "龙山区",
    distance: "2.4km",
    likes: 934,
    category: "攻略",
    following: true,
    topicKeywords: ["首尔", "夜景", "第一次", "拍照", "攻略"],
    allowedImageKeywords: ["seoul skyline", "city night", "korea city"],
    forbiddenImageKeywords: ["europe", "food", "bedroom"],
    imageSearchQuery: "seoul skyline night korea",
    imageCount: 1,
    curatedImages: [pexelsPhoto(2087028, "seoul skyline")],
  },
  {
    seedId: 53,
    title: "广藏市场人挤人但好吃",
    content:
      "周末去广藏市场，画面就是这种人挤人的档口。绿豆饼和血肠都可以试，现金备一点更方便。",
    author: "市场吃货",
    location: "钟路",
    distance: "3.8km",
    likes: 812,
    category: "探店",
    nearby: true,
    topicKeywords: ["广藏市场", "市场", "小吃", "探店", "周末"],
    allowedImageKeywords: ["market", "street food", "asian market", "bazaar"],
    forbiddenImageKeywords: ["europe", "bedroom", "laptop"],
    imageSearchQuery: "asian street market food",
    imageCount: 2,
    curatedImages: [
      pexelsPhoto(2313686, "asian street market"),
      pexelsPhoto(7319149, "street food stall"),
    ],
  },
  {
    seedId: 54,
    title: "CU新品试吃跑三家店",
    content:
      "图是便利店货架前挑新品，这次试了三家CU。饭团和甜品有新口味，韩文看不懂就拍图翻译。",
    author: "便利店测评",
    location: "新村",
    distance: "100m",
    likes: 467,
    category: "探店",
    nearby: true,
    topicKeywords: ["CU", "便利店", "新品", "探店", "测评"],
    allowedImageKeywords: ["convenience store", "snacks", "store shelf", "shop"],
    forbiddenImageKeywords: ["europe", "landscape", "hiking"],
    imageSearchQuery: "convenience store snacks asia",
    imageCount: 2,
    curatedImages: [
      pexelsPhoto(7625056, "convenience store"),
      pexelsPhoto(1071882, "instant noodles snack"),
    ],
  },
  {
    seedId: 55,
    title: "Olive Young大促我囤这些",
    content:
      "大促去明洞Olive Young，图里就是结账前那堆 skincare。面膜和防晒可以多囤，记得看保质期。",
    author: "护肤囤货党",
    location: "明洞",
    distance: "350m",
    likes: 689,
    category: "攻略",
    nearby: true,
    following: true,
    topicKeywords: ["Olive Young", "护肤", "大促", "囤货", "攻略"],
    allowedImageKeywords: ["skincare", "beauty products", "cosmetics", "shopping"],
    forbiddenImageKeywords: ["europe", "food", "landscape"],
    imageSearchQuery: "skincare beauty products flat lay",
    imageCount: 2,
    curatedImages: [
      pexelsPhoto(5637522, "skincare products"),
      pexelsPhoto(996329, "beauty store"),
    ],
  },
  {
    seedId: 56,
    title: "出安卓机屏幕无划痕",
    content:
      "转让备用安卓机，照片就是平时拍的状态，屏幕没有明显划痕。面交试机，新村或延世附近都可以。",
    author: "安卓换果",
    location: "新村",
    distance: "350m",
    likes: 198,
    category: "二手",
    nearby: true,
    topicKeywords: ["安卓", "手机", "二手", "转让", "屏幕"],
    allowedImageKeywords: ["smartphone", "mobile phone", "phone", "android"],
    forbiddenImageKeywords: ["europe", "food", "landscape"],
    imageSearchQuery: "smartphone hand bright",
    imageCount: 1,
    curatedImages: [pexelsPhoto(607812, "smartphone")],
  },
  {
    seedId: 57,
    title: "备用机盒说全如图",
    content:
      "iPhone备用机出手，图是放桌上的实拍，配件盒说都在。电池健康80%+，适合当副机。",
    author: "双机党",
    location: "江南站",
    distance: "800m",
    likes: 276,
    category: "二手",
    nearby: true,
    topicKeywords: ["iPhone", "备用机", "二手", "盒说全", "转让"],
    allowedImageKeywords: ["iphone", "smartphone", "mobile phone"],
    forbiddenImageKeywords: ["europe", "food", "bedroom"],
    imageSearchQuery: "iphone smartphone table",
    imageCount: 2,
    curatedImages: [
      pexelsPhoto(788946, "iphone smartphone"),
      pexelsPhoto(607812, "mobile phone"),
    ],
  },
  {
    seedId: 58,
    title: "理线后出的2K显示器",
    content:
      "27寸2K显示器转让，图就是现在桌面这样，理线后干净很多。延寿区自取，带DP线。",
    author: "桌面控",
    location: "延寿区",
    distance: "2.4km",
    likes: 145,
    category: "二手",
    nearby: true,
    topicKeywords: ["显示器", "2K", "二手", "桌面", "转让"],
    allowedImageKeywords: ["monitor", "computer screen", "desk setup"],
    forbiddenImageKeywords: ["europe", "food", "landscape"],
    imageSearchQuery: "computer monitor desk setup",
    imageCount: 1,
    curatedImages: [pexelsPhoto(777001, "computer monitor")],
  },
  {
    seedId: 59,
    title: "毕业出书桌就是这张",
    content:
      "要出的书桌就是照片里这个角度，120x60，带抽屉。水原站附近自提，可以帮拆腿。",
    author: "水原毕业生",
    location: "水原站",
    distance: "3.8km",
    likes: 167,
    category: "二手",
    topicKeywords: ["书桌", "毕业", "二手", "出让", "家具"],
    allowedImageKeywords: ["desk", "study desk", "workspace", "furniture"],
    forbiddenImageKeywords: ["europe", "food", "landscape"],
    imageSearchQuery: "wooden study desk room",
    imageCount: 2,
    curatedImages: [
      pexelsPhoto(1957478, "study desk"),
      pexelsPhoto(777001, "desk workspace"),
    ],
  },
  {
    seedId: 60,
    title: "东大门打折淘到的外套",
    content:
      "东大门清仓淘的几件外套，图是其中一件上身前挂拍。均码偏多，砍价空间不大但比网店便宜。",
    author: "淘衣小妹",
    location: "东大门",
    distance: "100m",
    likes: 334,
    category: "二手",
    nearby: true,
    topicKeywords: ["东大门", "外套", "二手", "打折", "衣服"],
    allowedImageKeywords: ["clothes", "fashion", "clothing", "apparel"],
    forbiddenImageKeywords: ["europe", "food", "landscape"],
    imageSearchQuery: "clothes fashion rack",
    imageCount: 2,
    curatedImages: [
      pexelsPhoto(1926765, "clothes fashion"),
      pexelsPhoto(996329, "clothing store"),
    ],
  },
];
