import { pexelsPhoto } from "./pexels-url";
import type { AutoPostTemplate } from "./types";

/** Batch 3 (41–50): image-first — copy written after selecting Korea/China lifestyle photos. */
export const AUTO_POST_TEMPLATES_F: AutoPostTemplate[] = [
  {
    seedId: 41,
    title: "建大这桌烤肉就是我上次点的",
    content:
      "图里这盘五花肉和拼盘就是建大中国街后面那家。炭火烤到边缘微焦最好吃，生菜包蒜片真的绝。人均2.5万左右，晚6点前去不用排队。",
    author: "烤肉记录员",
    location: "建大",
    distance: "100m",
    likes: 892,
    category: "探店",
    nearby: true,
    following: true,
    imageFirst: true,
    requireImages: true,
    topicKeywords: ["烤肉", "五花肉", "建大", "探店", "韩餐"],
    allowedImageKeywords: ["korean bbq", "grill", "meat", "bbq", "restaurant"],
    forbiddenImageKeywords: ["europe", "landscape", "cathedral", "bedroom"],
    imageSearchQuery: "korean bbq grill table",
    imageCount: 2,
    curatedImages: [
      pexelsPhoto(6660060, "korean bbq grill"),
      pexelsPhoto(1267320, "grilled meat plate"),
    ],
  },
  {
    seedId: 42,
    title: "弘大夜市鱼饼串就长这样",
    content:
      "冬天在弘大路边摊买的鱼饼串，热汤免费续。照片就是拿到手那刻拍的，冒热气。一串1000韩币左右，逛完街来一串很治愈。",
    author: "夜市路人",
    location: "弘大",
    distance: "350m",
    likes: 654,
    category: "探店",
    nearby: true,
    topicKeywords: ["鱼饼", "夜市", "弘大", "路边摊", "小吃"],
    allowedImageKeywords: ["street food", "korean food", "snack", "market"],
    forbiddenImageKeywords: ["europe", "apartment", "laptop"],
    imageSearchQuery: "korean street food night",
    imageCount: 2,
    curatedImages: [
      pexelsPhoto(7319149, "korean street food"),
      pexelsPhoto(2313686, "asian night market"),
    ],
  },
  {
    seedId: 43,
    title: "新村饺子馆这盘水饺实拍",
    content:
      "图里就是新村地铁站附近中文饺子馆的水饺，现包现煮。皮不算厚，蘸醋加一点点辣椒油。一碟大概8个，8000韩币上下。",
    author: "北方胃",
    location: "新村",
    distance: "100m",
    likes: 421,
    category: "探店",
    nearby: true,
    topicKeywords: ["饺子", "水饺", "新村", "中餐", "探店"],
    allowedImageKeywords: ["dumplings", "chinese food", "dim sum", "meal"],
    forbiddenImageKeywords: ["europe", "landscape", "subway"],
    imageSearchQuery: "chinese dumplings plate",
    imageCount: 1,
    curatedImages: [pexelsPhoto(958545, "chinese dumplings")],
  },
  {
    seedId: 44,
    title: "明洞火锅红油锅底实拍",
    content:
      "照片就是上锅那瞬间，红油翻滚那种。在明洞中国街附近，适合3-4人。毛肚黄喉记得早点下，辣度可以选微辣。",
    author: "火锅脑袋",
    location: "明洞",
    distance: "350m",
    likes: 1034,
    category: "探店",
    nearby: true,
    following: true,
    topicKeywords: ["火锅", "红油", "明洞", "中餐", "探店"],
    allowedImageKeywords: ["hot pot", "chinese food", "spicy pot", "meal"],
    forbiddenImageKeywords: ["europe", "bedroom", "hiking"],
    imageSearchQuery: "chinese hot pot spicy",
    imageCount: 2,
    curatedImages: [
      pexelsPhoto(699953, "chinese hot pot"),
      pexelsPhoto(725997, "restaurant dining"),
    ],
  },
  {
    seedId: 45,
    title: "建大后门这碗拉面实物",
    content:
      "就是学校后面日式拉面店的那碗，汤挺浓，叉烧片不大但够味。下课点去会排队，建议错开12点半。",
    author: "拉面课代表",
    location: "建大",
    distance: "800m",
    likes: 367,
    category: "探店",
    nearby: true,
    topicKeywords: ["拉面", "建大", "日式", "探店", "美食"],
    allowedImageKeywords: ["ramen", "noodles", "japanese food", "bowl"],
    forbiddenImageKeywords: ["europe", "landscape", "apartment"],
    imageSearchQuery: "ramen bowl asian",
    imageCount: 1,
    curatedImages: [pexelsPhoto(1835928, "ramen bowl")],
  },
  {
    seedId: 46,
    title: "江南这杯奶茶三分糖刚好",
    content:
      "图里就是拿到手的黑糖珍珠，冰还没化。江南站后面那条街，中文点单没问题。三分糖真的不齁，夏天走累了来一杯。",
    author: "奶茶半糖",
    location: "江南站",
    distance: "100m",
    likes: 578,
    category: "探店",
    nearby: true,
    topicKeywords: ["奶茶", "珍珠", "江南", "三分糖", "探店"],
    allowedImageKeywords: ["bubble tea", "milk tea", "boba", "drink"],
    forbiddenImageKeywords: ["europe", "landscape", "monitor"],
    imageSearchQuery: "bubble tea boba drink",
    imageCount: 2,
    curatedImages: [
      pexelsPhoto(1537977, "bubble tea"),
      pexelsPhoto(376464, "cafe latte drink"),
    ],
  },
  {
    seedId: 47,
    title: "梨泰院这杯拉花咖啡稳的",
    content:
      "周末在梨泰院找地方写东西，点了拿铁。拉花就是图上这样，店里音乐不大，适合坐一下午。",
    author: "咖啡续命中",
    location: "梨泰院",
    distance: "1.2km",
    likes: 445,
    category: "探店",
    following: true,
    topicKeywords: ["咖啡", "拉花", "梨泰院", "拿铁", "探店"],
    allowedImageKeywords: ["latte", "coffee", "cafe", "coffee art"],
    forbiddenImageKeywords: ["europe", "landscape", "bedroom"],
    imageSearchQuery: "latte coffee art cafe",
    imageCount: 1,
    curatedImages: [pexelsPhoto(376464, "latte coffee art")],
  },
  {
    seedId: 48,
    title: "延世后门美式早八必备",
    content:
      "早八课前在后门这家买美式，图是柜台现做那杯。价格不贵，豆子偏深烘。韩文菜单看不懂就指美式就行。",
    author: "早八战士",
    location: "延世大学",
    distance: "100m",
    likes: 312,
    category: "探店",
    nearby: true,
    topicKeywords: ["美式", "咖啡", "延世", "早八", "探店"],
    allowedImageKeywords: ["coffee", "cafe", "barista", "coffee shop"],
    forbiddenImageKeywords: ["europe", "landscape", "phone"],
    imageSearchQuery: "coffee shop morning cafe",
    imageCount: 2,
    curatedImages: [
      pexelsPhoto(324028, "barista coffee"),
      pexelsPhoto(302899, "coffee shop"),
    ],
  },
  {
    seedId: 49,
    title: "转租单间窗景就是这样",
    content:
      "要转的单间实拍，图里窗外就是普通居民区，光线下午挺好。家电齐全，合同还有8个月，建国大学步行10分钟。",
    author: "转租本人",
    location: "建国大学",
    distance: "350m",
    likes: 289,
    category: "房屋",
    nearby: true,
    topicKeywords: ["转租", "单间", "窗景", "建国大学", "租房"],
    allowedImageKeywords: ["bedroom", "apartment", "room", "interior"],
    forbiddenImageKeywords: ["europe", "food", "landscape"],
    imageSearchQuery: "small apartment bedroom window",
    imageCount: 2,
    curatedImages: [
      pexelsPhoto(1571460, "apartment bedroom", { portrait: true }),
      pexelsPhoto(271743, "cozy bedroom"),
    ],
  },
  {
    seedId: 50,
    title: "弘大oneroom白色床单这间",
    content:
      "图就是我现在住的弘大oneroom，白色床单是自己买的。房间不大但够用，月租包网。下月搬去公司附近，所以转。",
    author: "弘大住户",
    location: "弘大",
    distance: "350m",
    likes: 356,
    category: "房屋",
    nearby: true,
    topicKeywords: ["oneroom", "弘大", "转租", "单间", "租房"],
    allowedImageKeywords: ["bedroom", "studio", "apartment", "room"],
    forbiddenImageKeywords: ["europe", "food", "landscape"],
    imageSearchQuery: "studio room white bedroom",
    imageCount: 2,
    curatedImages: [
      pexelsPhoto(271743, "white bedroom"),
      pexelsPhoto(439391, "studio room"),
    ],
  },
];
