import type { AutoPostTemplate } from "./types";

export const AUTO_POST_TEMPLATES_C: AutoPostTemplate[] = [
  {
    seedId: 12,
    title: "韩国通信卡怎么选最划算",
    content:
      "韩国通信卡选购指南：短期旅游选预付卡，长期留学可考虑先付后付。对比了几家运营商流量和通话套餐，附办理地点。",
    author: "通讯小助手",
    location: "建国大学",
    distance: "2.4km",
    likes: 1678,
    category: "其他",
    following: true,
    topicKeywords: ["通信卡", "流量", "套餐", "韩国", "手机"],
    allowedImageKeywords: ["sim card", "smartphone", "mobile phone", "phone"],
    forbiddenImageKeywords: ["food", "landscape", "bedroom", "hiking"],
    imageSearchQuery: "smartphone sim card bright lifestyle",
    imageCount: 1,
    curatedImages: [
      {
        url: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&q=80",
        width: 800,
        height: 533,
        keyword: "smartphone",
        source: "unsplash",
      },
      {
        url: "https://images.pexels.com/photos/607812/pexels-photo-607812.jpeg?auto=compress&cs=tinysrgb&w=800",
        width: 800,
        height: 533,
        keyword: "mobile phone",
        source: "pexels",
      },
    ],
  },
  {
    seedId: 13,
    title: "餐馆急招周末帮厨",
    content:
      "海云台餐馆急招周末帮厨，主要负责备菜和清洁。包餐，工作氛围好，有餐饮经验者优先，工资周结。",
    author: "釜山老板",
    location: "海云台",
    distance: "3.8km",
    likes: 145,
    category: "招聘",
    topicKeywords: ["帮厨", "周末", "餐馆", "招聘", "海云台"],
    allowedImageKeywords: ["kitchen", "chef", "cooking", "restaurant kitchen", "food prep"],
    forbiddenImageKeywords: ["landscape", "bedroom", "laptop", "hiking"],
    imageSearchQuery: "restaurant kitchen chef cooking bright",
    imageCount: 2,
    curatedImages: [
      {
        url: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800&q=80",
        width: 800,
        height: 533,
        keyword: "restaurant kitchen",
        source: "unsplash",
      },
      {
        url: "https://images.pexels.com/photos/1267320/pexels-photo-1267320.jpeg?auto=compress&cs=tinysrgb&w=800",
        width: 800,
        height: 533,
        keyword: "food cooking",
        source: "pexels",
      },
    ],
  },
  {
    seedId: 14,
    title: "求推荐靠谱中文牙医",
    content:
      "大田站附近有没有靠谱的中文牙医推荐？最近牙疼需要检查，希望沟通方便、价格透明，有经历的朋友请分享。",
    author: "牙疼求助",
    location: "大田站",
    distance: "2.4km",
    likes: 312,
    category: "求助",
    topicKeywords: ["牙医", "牙疼", "推荐", "求助", "中文"],
    allowedImageKeywords: ["dentist", "dental", "clinic", "teeth", "healthcare"],
    forbiddenImageKeywords: ["food", "landscape", "bedroom", "bbq"],
    imageSearchQuery: "dental clinic dentist bright clean",
    imageCount: 1,
    curatedImages: [
      {
        url: "https://images.unsplash.com/photo-1629907338208-64cd36c8e9f0?w=800&q=80",
        width: 800,
        height: 533,
        keyword: "dental clinic",
        source: "unsplash",
      },
      {
        url: "https://images.pexels.com/photos/3845810/pexels-photo-3845810.jpeg?auto=compress&cs=tinysrgb&w=800",
        width: 800,
        height: 533,
        keyword: "dentist",
        source: "pexels",
      },
    ],
  },
  {
    seedId: 15,
    title: "二手 MacBook Air M1",
    content:
      "转让二手 MacBook Air M1，8G+256G，电池健康90%+，无维修史。松坡区面交，可验机，价格可聊。",
    author: "苹果用户",
    location: "松坡区",
    distance: "800m",
    likes: 456,
    category: "二手",
    nearby: true,
    following: true,
    topicKeywords: ["MacBook", "M1", "二手", "苹果", "转让"],
    allowedImageKeywords: ["macbook", "laptop", "apple laptop", "notebook"],
    forbiddenImageKeywords: ["food", "landscape", "bedroom", "running"],
    imageSearchQuery: "macbook laptop desk bright natural light",
    imageCount: 3,
    curatedImages: [
      {
        url: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&q=80",
        width: 800,
        height: 533,
        keyword: "macbook laptop",
        source: "unsplash",
      },
      {
        url: "https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=800",
        width: 800,
        height: 533,
        keyword: "apple laptop",
        source: "pexels",
      },
    ],
  },
  {
    seedId: 16,
    title: "夜跑团招募新成员",
    content:
      "蚕室夜跑团招募新成员，每周二四晚上8点集合，配速友好。欢迎想坚持运动的朋友加入，一起打卡汉江。",
    author: "跑步搭子",
    location: "蚕室",
    distance: "1.2km",
    likes: 623,
    category: "其他",
    nearby: true,
    topicKeywords: ["夜跑", "跑步", "搭子", "招募", "运动"],
    allowedImageKeywords: ["running", "jogging", "runners", "night run", "fitness"],
    forbiddenImageKeywords: ["food", "bedroom", "monitor", "dentist"],
    imageSearchQuery: "people running outdoors bright evening",
    imageCount: 2,
    curatedImages: [
      {
        url: "https://images.unsplash.com/photo-1476480862126-209dbaaadcde?w=800&q=80",
        width: 800,
        height: 533,
        keyword: "people running",
        source: "unsplash",
      },
      {
        url: "https://images.pexels.com/photos/2803158/pexels-photo-2803158.jpeg?auto=compress&cs=tinysrgb&w=800",
        width: 800,
        height: 533,
        keyword: "jogging fitness",
        source: "pexels",
      },
    ],
  },
  {
    seedId: 17,
    title: "高丽大租房经验分享",
    content:
      "在高丽大附近租房一年的经验：看房注意采光和隔音，签约前确认管理费。整理了常见坑和推荐区域，供学弟学妹参考。",
    author: "高大学长",
    location: "高丽大",
    distance: "350m",
    likes: 934,
    category: "攻略",
    following: true,
    topicKeywords: ["租房", "高丽大", "经验", "攻略", "看房"],
    allowedImageKeywords: ["apartment", "bedroom", "room", "housing", "interior"],
    forbiddenImageKeywords: ["food", "landscape", "phone", "running"],
    imageSearchQuery: "student apartment room bright korea",
    imageCount: 2,
    curatedImages: [
      {
        url: "https://images.pexels.com/photos/1571463/pexels-photo-1571463.jpeg?auto=compress&cs=tinysrgb&w=800",
        width: 800,
        height: 533,
        keyword: "student apartment",
        source: "pexels",
      },
      {
        url: "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80",
        width: 800,
        height: 533,
        keyword: "apartment interior",
        source: "unsplash",
      },
    ],
  },
  {
    seedId: 18,
    title: "延世附近兼职家教",
    content:
      "延世大学附近招兼职家教，辅导中学生英语/数学，时间灵活。时薪优厚，要求有耐心，有家教经验者优先。",
    author: "家教老师",
    location: "延世大学",
    distance: "100m",
    likes: 187,
    category: "招聘",
    nearby: true,
    topicKeywords: ["家教", "兼职", "延世", "招聘", "辅导"],
    allowedImageKeywords: ["tutoring", "study", "books", "classroom", "learning", "school"],
    forbiddenImageKeywords: ["food", "landscape", "monitor", "running"],
    imageSearchQuery: "tutoring study books bright classroom",
    imageCount: 1,
    curatedImages: [
      {
        url: "https://images.unsplash.com/photo-1434030216411-0b793089c25f?w=800&q=80",
        width: 800,
        height: 533,
        keyword: "study books",
        source: "unsplash",
      },
      {
        url: "https://images.pexels.com/photos/159711/books-bookstore-book-reading-159711.jpeg?auto=compress&cs=tinysrgb&w=800",
        width: 800,
        height: 533,
        keyword: "learning tutoring",
        source: "pexels",
      },
    ],
  },
  {
    seedId: 19,
    title: "入境接机拼车有人吗",
    content:
      "新生报到，仁川机场入境后想拼车去首尔市区。预计周日下午到达，2-3人分摊费用更划算，有同路的同学联系。",
    author: "新生报到",
    location: "仁川机场",
    distance: "3.8km",
    likes: 98,
    category: "求助",
    nearby: true,
    topicKeywords: ["接机", "拼车", "仁川机场", "入境", "新生"],
    allowedImageKeywords: ["airport", "airplane", "terminal", "travel", "luggage"],
    forbiddenImageKeywords: ["food", "bedroom", "bbq", "dentist"],
    imageSearchQuery: "airport terminal travelers bright",
    imageCount: 2,
    curatedImages: [
      {
        url: "https://images.unsplash.com/photo-1436450412630-467171c7bb57?w=800&q=80",
        width: 800,
        height: 533,
        keyword: "airport terminal",
        source: "unsplash",
      },
      {
        url: "https://images.pexels.com/photos/912050/pexels-photo-912050.jpeg?auto=compress&cs=tinysrgb&w=800",
        width: 800,
        height: 533,
        keyword: "airplane travel",
        source: "pexels",
      },
    ],
  },
  {
    seedId: 20,
    title: "釜山美食打卡清单",
    content:
      "釜山海云台美食打卡清单：海鲜市场、猪肉汤饭、韩式炸物都试了。按口味和排队时间排了个优先级，周末去釜山可参考。",
    author: "釜山吃货",
    location: "海云台",
    distance: "1.2km",
    likes: 1567,
    category: "探店",
    topicKeywords: ["釜山", "美食", "打卡", "海云台", "探店"],
    allowedImageKeywords: ["seafood", "korean food", "meal", "restaurant", "dining"],
    forbiddenImageKeywords: ["apartment", "landscape", "laptop", "school"],
    imageSearchQuery: "korean seafood meal restaurant bright",
    imageCount: 3,
    curatedImages: [
      {
        url: "https://images.unsplash.com/photo-1563245372-f21724e3850f?w=800&q=80",
        width: 800,
        height: 533,
        keyword: "seafood meal",
        source: "unsplash",
      },
      {
        url: "https://images.pexels.com/photos/725997/pexels-photo-725997.jpeg?auto=compress&cs=tinysrgb&w=800",
        width: 800,
        height: 533,
        keyword: "korean dining",
        source: "pexels",
      },
    ],
  },
];
