import type { AutoPostTemplate } from "./types";

function pexels(
  id: number,
  keyword: string,
  width = 800,
  height: number = width === 800 ? 533 : 1067,
): AutoPostTemplate["curatedImages"][number] {
  return {
    url: `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=800`,
    width,
    height,
    keyword,
    source: "pexels",
  };
}

export const AUTO_POST_TEMPLATES_D: AutoPostTemplate[] = [
  {
    seedId: 21,
    title: "梨大附近整租两室 近地铁",
    content:
      "梨大南门附近两室一厅整租，步行到地铁站约6分钟。家电齐全，采光不错，适合两人合租，合同可续。",
    author: "梨大租客",
    location: "梨大",
    distance: "350m",
    likes: 445,
    category: "房屋",
    nearby: true,
    topicKeywords: ["整租", "两室", "梨大", "地铁", "租房"],
    allowedImageKeywords: ["apartment", "living room", "bedroom", "interior", "housing"],
    forbiddenImageKeywords: ["food", "landscape", "phone", "running"],
    imageSearchQuery: "bright apartment living room natural light",
    imageCount: 2,
    curatedImages: [pexels(1457842, "living room"), pexels(271624, "modern apartment")],
  },
  {
    seedId: 22,
    title: "明洞网红炸鸡店实测",
    content:
      "明洞这家炸鸡店外酥里嫩，酱油和甜辣都好吃。建议避开饭点，人均1.5-2万韩币，打包回宿舍也合适。",
    author: "炸鸡控",
    location: "明洞",
    distance: "100m",
    likes: 876,
    category: "探店",
    nearby: true,
    following: true,
    topicKeywords: ["炸鸡", "明洞", "探店", "美食", "网红"],
    allowedImageKeywords: ["fried chicken", "chicken", "korean food", "meal", "restaurant"],
    forbiddenImageKeywords: ["apartment", "landscape", "laptop", "school"],
    imageSearchQuery: "fried chicken korean food restaurant bright",
    imageCount: 2,
    curatedImages: [pexels(1267320, "korean food"), pexels(1640777, "restaurant meal")],
  },
  {
    seedId: 23,
    title: "弘大数据号周末店员招聘",
    content:
      "弘大周边文创店招周末店员，负责收银和陈列。韩语基础即可，时薪1.1万，排班灵活，有零售经验优先。",
    author: "弘大店主",
    location: "弘大",
    distance: "350m",
    likes: 132,
    category: "招聘",
    nearby: true,
    topicKeywords: ["店员", "周末", "弘大", "招聘", "兼职"],
    allowedImageKeywords: ["retail", "shop", "store", "cashier", "work"],
    forbiddenImageKeywords: ["bedroom", "landscape", "food", "hiking"],
    imageSearchQuery: "bright retail shop store natural light",
    imageCount: 1,
    curatedImages: [pexels(996329, "retail shop"), pexels(5632402, "store interior")],
  },
  {
    seedId: 24,
    title: "出二手 iPhone 13 128G",
    content:
      "自用 iPhone 13 128G 转让，电池健康86%，无维修。面交验机，松坡区或蚕室站附近，价格可聊。",
    author: "果粉小王",
    location: "蚕室",
    distance: "800m",
    likes: 367,
    category: "二手",
    nearby: true,
    topicKeywords: ["iPhone", "13", "二手", "转让", "手机"],
    allowedImageKeywords: ["iphone", "smartphone", "mobile phone", "phone"],
    forbiddenImageKeywords: ["food", "landscape", "bedroom", "running"],
    imageSearchQuery: "iphone smartphone bright lifestyle",
    imageCount: 2,
    curatedImages: [pexels(607812, "smartphone"), pexels(788946, "mobile phone")],
  },
  {
    seedId: 25,
    title: "外国人ARC延期一次过攻略",
    content:
      "ARC延期实战经验：材料清单、预约技巧、常见拒签原因都整理了。建议提前两周准备，现场沟通保持礼貌。",
    author: "延签达人",
    location: "九老",
    distance: "2.4km",
    likes: 1289,
    category: "攻略",
    following: true,
    topicKeywords: ["ARC", "延期", "攻略", "外国人", "登陆证"],
    allowedImageKeywords: ["passport", "documents", "paperwork", "visa", "office"],
    forbiddenImageKeywords: ["food", "landscape", "bedroom", "bbq"],
    imageSearchQuery: "passport documents desk bright",
    imageCount: 1,
    curatedImages: [pexels(636243, "passport documents"), pexels(7688336, "office paperwork")],
  },
  {
    seedId: 26,
    title: "高丽大图书馆自习搭子",
    content:
      "寻找高丽大中央图书馆自习搭子，工作日晚上或周末白天都可。希望互相监督，不玩手机，一起备考期末。",
    author: "备考人",
    location: "高丽大",
    distance: "100m",
    likes: 512,
    category: "其他",
    nearby: true,
    following: true,
    topicKeywords: ["自习", "图书馆", "搭子", "高丽大", "备考"],
    allowedImageKeywords: ["library", "study", "books", "learning", "reading"],
    forbiddenImageKeywords: ["food", "landscape", "monitor", "running"],
    imageSearchQuery: "library study books bright",
    imageCount: 2,
    curatedImages: [pexels(159711, "study books"), pexels(207662, "library reading")],
  },
  {
    seedId: 27,
    title: "江南站一居室急转租",
    content:
      "江南站步行8分钟一居室急转租，带洗衣机和冰箱。因实习结束回国，合同剩余4个月，可短租可续。",
    author: "江南转租",
    location: "江南站",
    distance: "800m",
    likes: 298,
    category: "房屋",
    nearby: true,
    topicKeywords: ["一居室", "转租", "江南", "急转", "租房"],
    allowedImageKeywords: ["apartment", "bedroom", "studio", "interior", "housing"],
    forbiddenImageKeywords: ["food", "landscape", "phone", "hiking"],
    imageSearchQuery: "studio apartment bedroom bright cozy",
    imageCount: 2,
    curatedImages: [pexels(1571460, "apartment bedroom"), pexels(439391, "studio room")],
  },
  {
    seedId: 28,
    title: "韩国T-money交通卡使用指南",
    content:
      "T-money和Cashbee怎么选、怎么充值、换乘优惠怎么用，一篇讲清楚。便利店和地铁站都能充，记得刷卡出站。",
    author: "通勤指南",
    location: "首尔",
    distance: "1.2km",
    likes: 1543,
    category: "其他",
    topicKeywords: ["T-money", "交通卡", "充值", "地铁", "韩国"],
    allowedImageKeywords: ["subway", "metro", "transit card", "train", "commute"],
    forbiddenImageKeywords: ["food", "landscape", "bedroom", "bbq"],
    imageSearchQuery: "subway metro station bright commute",
    imageCount: 1,
    curatedImages: [pexels(912966, "subway metro"), pexels(13825208, "metro station")],
  },
  {
    seedId: 29,
    title: "烤肉店平日晚班服务员",
    content:
      "建大附近烤肉店招平日晚班服务员，主要负责上菜和收桌。包一顿餐，韩语一般即可，周结工资。",
    author: "建大烤肉店",
    location: "建大",
    distance: "100m",
    likes: 178,
    category: "招聘",
    nearby: true,
    topicKeywords: ["服务员", "晚班", "烤肉店", "招聘", "建大"],
    allowedImageKeywords: ["restaurant", "dining", "bbq", "korean food", "waiter"],
    forbiddenImageKeywords: ["landscape", "bedroom", "laptop", "school"],
    imageSearchQuery: "korean bbq restaurant dining bright",
    imageCount: 2,
    curatedImages: [pexels(1267320, "korean bbq"), pexels(725997, "restaurant dining")],
  },
  {
    seedId: 30,
    title: "求推荐中文儿科诊所",
    content:
      "宝宝最近咳嗽，想找会说中文的儿科诊所。最好在江南或瑞草附近，有带娃经验的朋友求推荐。",
    author: "新手爸妈",
    location: "江南",
    distance: "2.4km",
    likes: 245,
    category: "求助",
    topicKeywords: ["儿科", "中文", "推荐", "求助", "诊所"],
    allowedImageKeywords: ["clinic", "pediatric", "healthcare", "hospital", "medical"],
    forbiddenImageKeywords: ["food", "landscape", "bedroom", "bbq"],
    imageSearchQuery: "pediatric clinic healthcare bright clean",
    imageCount: 1,
    curatedImages: [pexels(3845810, "medical clinic"), pexels(4021779, "healthcare")],
  },
];
