import { pexelsPhoto } from "./pexels-url";
import type { AutoPostTemplate } from "./types";

/** Batch 3 (61–70): image-first commute / travel / 搭子 / 求助. */
export const AUTO_POST_TEMPLATES_H: AutoPostTemplate[] = [
  {
    seedId: 61,
    title: "2号线晚高峰就这样挤",
    content:
      "给新生看地铁晚高峰，照片就是2号线常见密度。刷卡进出别忘了tap out，换乘走指示蓝线。",
    author: "地铁老司机",
    location: "建大入口",
    distance: "350m",
    likes: 1123,
    category: "攻略",
    nearby: true,
    following: true,
    imageFirst: true,
    requireImages: true,
    topicKeywords: ["2号线", "地铁", "晚高峰", "攻略", "换乘"],
    allowedImageKeywords: ["subway", "metro", "train", "commute"],
    forbiddenImageKeywords: ["europe", "food", "bedroom"],
    imageSearchQuery: "subway metro asia commute",
    imageCount: 2,
    curatedImages: [
      pexelsPhoto(912966, "subway metro"),
      pexelsPhoto(13825208, "metro station"),
    ],
  },
  {
    seedId: 62,
    title: "T-money充值机长这样",
    content:
      "地铁站里充值机界面就是图里这种，中文可以切。现金和刷卡都行，余额低于5000记得充。",
    author: "通勤指南",
    location: "江南站",
    distance: "800m",
    likes: 876,
    category: "其他",
    topicKeywords: ["T-money", "充值", "地铁", "交通卡", "攻略"],
    allowedImageKeywords: ["metro", "subway", "transit", "station"],
    forbiddenImageKeywords: ["europe", "food", "landscape"],
    imageSearchQuery: "metro station korea transit",
    imageCount: 1,
    curatedImages: [pexelsPhoto(13825208, "metro station")],
  },
  {
    seedId: 63,
    title: "ARC延期材料我摆桌上拍",
    content:
      "延期前我把护照、申请表和收据摆桌上拍了张备忘。大家去之前核对清单，少一样都要重跑。",
    author: "延签过来人",
    location: "九老",
    distance: "2.4km",
    likes: 1456,
    category: "攻略",
    following: true,
    topicKeywords: ["ARC", "延期", "材料", "护照", "攻略"],
    allowedImageKeywords: ["passport", "documents", "paperwork", "visa"],
    forbiddenImageKeywords: ["europe", "food", "landscape"],
    imageSearchQuery: "passport documents desk",
    imageCount: 2,
    curatedImages: [
      pexelsPhoto(636243, "passport documents"),
      pexelsPhoto(7688336, "office paperwork"),
    ],
  },
  {
    seedId: 64,
    title: "落地仁川两个28寸箱",
    content:
      "刚落地推的两个28寸，就是照片这样。建议新生买绑带，转机别拖太慢挡路。",
    author: "落地第一天",
    location: "仁川机场",
    distance: "3.8km",
    likes: 234,
    category: "求助",
    nearby: true,
    topicKeywords: ["仁川", "行李", "28寸", "落地", "新生"],
    allowedImageKeywords: ["luggage", "suitcase", "travel", "airport"],
    forbiddenImageKeywords: ["europe", "food", "bedroom"],
    imageSearchQuery: "luggage suitcase airport travel",
    imageCount: 2,
    curatedImages: [
      pexelsPhoto(424614, "luggage suitcase"),
      pexelsPhoto(912050, "airport travel"),
    ],
  },
  {
    seedId: 65,
    title: "T1到达层拼车在这碰头",
    content:
      "约拼车可以约在T1到达层这个区域，图是常见碰头点方向。记得发航班号，晚点到提前说。",
    author: "接机老手",
    location: "仁川机场",
    distance: "3.8km",
    likes: 189,
    category: "求助",
    nearby: true,
    topicKeywords: ["T1", "拼车", "仁川", "接机", "到达"],
    allowedImageKeywords: ["airport", "terminal", "travel", "airplane"],
    forbiddenImageKeywords: ["europe", "food", "bedroom"],
    imageSearchQuery: "airport terminal arrival",
    imageCount: 1,
    curatedImages: [pexelsPhoto(912050, "airport terminal")],
  },
  {
    seedId: 66,
    title: "汉江夜跑小队配速友好",
    content:
      "周二四晚上汉江边慢跑，照片是集合点附近。配速不快，新手也能跟，跑完一起拉伸。",
    author: "夜跑队长",
    location: "蚕室",
    distance: "1.2km",
    likes: 612,
    category: "其他",
    nearby: true,
    following: true,
    topicKeywords: ["夜跑", "汉江", "跑步", "搭子", "慢跑"],
    allowedImageKeywords: ["running", "jogging", "fitness", "outdoor"],
    forbiddenImageKeywords: ["europe", "food", "bedroom"],
    imageSearchQuery: "people jogging night outdoor",
    imageCount: 2,
    curatedImages: [
      pexelsPhoto(2803158, "jogging fitness"),
      pexelsPhoto(248547, "outdoor exercise"),
    ],
  },
  {
    seedId: 67,
    title: "汝矣岛骑车风大但出片",
    content:
      "周末在汝矣岛租公共自行车，照片就是骑到江边那刻。风很大戴帽子， sunset 时段更好看。",
    author: "骑车党",
    location: "汝矣岛",
    distance: "2.4km",
    likes: 498,
    category: "其他",
    nearby: true,
    topicKeywords: ["骑车", "汝矣岛", "汉江", "搭子", "周末"],
    allowedImageKeywords: ["cycling", "bicycle", "bike", "outdoor"],
    forbiddenImageKeywords: ["europe", "food", "bedroom"],
    imageSearchQuery: "cycling bicycle riverside",
    imageCount: 2,
    curatedImages: [
      pexelsPhoto(248547, "cycling bicycle"),
      pexelsPhoto(1365425, "outdoor activity"),
    ],
  },
  {
    seedId: 68,
    title: "北汉山周末爬山腿抖值",
    content:
      "北汉山中级路线，照片是中途休息拍的下山方向。穿防滑鞋，带水和小零食，别单独行动。",
    author: "爬山搭子",
    location: "北汉山",
    distance: "3.8km",
    likes: 567,
    category: "其他",
    topicKeywords: ["北汉山", "爬山", "周末", "搭子", "户外"],
    allowedImageKeywords: ["hiking", "trail", "mountain", "outdoor"],
    forbiddenImageKeywords: ["europe", "food", "bedroom"],
    imageSearchQuery: "hiking trail korea mountain",
    imageCount: 2,
    curatedImages: [
      pexelsPhoto(1365425, "hiking trail"),
      pexelsPhoto(2803158, "outdoor trekking"),
    ],
  },
  {
    seedId: 69,
    title: "高丽大自习我常坐这区",
    content:
      "期末泡馆，图里就是我常坐的那片区域，插座够多。占座别用太多东西，饭点记得去吃饭。",
    author: "期末人",
    location: "高丽大",
    distance: "100m",
    likes: 734,
    category: "其他",
    nearby: true,
    topicKeywords: ["自习", "图书馆", "高丽大", "期末", "搭子"],
    allowedImageKeywords: ["library", "study", "books", "reading"],
    forbiddenImageKeywords: ["europe", "food", "landscape"],
    imageSearchQuery: "library study reading books",
    imageCount: 2,
    curatedImages: [
      pexelsPhoto(207662, "library reading"),
      pexelsPhoto(7688336, "study desk books"),
    ],
  },
  {
    seedId: 70,
    title: "洗完牙诊所环境挺亮",
    content:
      "大田这边中文沟通还行的牙科，图是洗完牙等复查拍的候诊区。预约制，Walk-in基本排不上。",
    author: "牙疼好了",
    location: "大田站",
    distance: "2.4km",
    likes: 389,
    category: "求助",
    topicKeywords: ["牙科", "洗牙", "诊所", "大田", "推荐"],
    allowedImageKeywords: ["dental", "clinic", "healthcare", "medical"],
    forbiddenImageKeywords: ["europe", "food", "landscape"],
    imageSearchQuery: "dental clinic bright clean",
    imageCount: 1,
    curatedImages: [pexelsPhoto(3845810, "dental clinic")],
  },
];
