import { pexelsPhoto } from "./pexels-url";
import type { AutoPostTemplate } from "./types";

/** Batch 4 (71–80): 당근마켓风格 — 原创中文同城二手/面交帖，非抓取转载。 */
export const AUTO_POST_TEMPLATES_I: AutoPostTemplate[] = [
  {
    seedId: 71,
    title: "弘大당근出九成新电风扇 面交2万",
    content:
      "夏天快到了，당근上挂的立式风扇，九成新，风力三档都正常。弘大站6号口面交，2万韩币，不邮寄。图就是实物，叶片已擦干净。",
    author: "弘大出清",
    location: "弘大",
    distance: "350m",
    likes: 89,
    category: "二手",
    nearby: true,
    imageFirst: true,
    requireImages: true,
    topicKeywords: ["당근", "电风扇", "弘大", "面交", "二手"],
    allowedImageKeywords: ["fan", "appliance", "home", "electric fan"],
    forbiddenImageKeywords: ["europe", "food", "landscape"],
    imageSearchQuery: "electric fan home appliance",
    imageCount: 2,
    curatedImages: [
      pexelsPhoto(1148955, "electric fan"),
      pexelsPhoto(1571460, "apartment room"),
    ],
  },
  {
    seedId: 72,
    title: "建大附近당근出微波炉 自取",
    content:
      "毕业出微波炉，당근同城交易。加热正常，内胆已清洁。建大正门口自取，3.5万可小刀，图是刚擦完拍的。",
    author: "建大毕业季",
    location: "建大",
    distance: "100m",
    likes: 56,
    category: "二手",
    nearby: true,
    topicKeywords: ["微波炉", "당근", "建大", "自取", "二手"],
    allowedImageKeywords: ["microwave", "kitchen", "appliance"],
    forbiddenImageKeywords: ["europe", "landscape", "phone"],
    imageSearchQuery: "microwave kitchen appliance",
    imageCount: 1,
    curatedImages: [pexelsPhoto(2724749, "microwave kitchen")],
  },
  {
    seedId: 73,
    title: "당근上淘到的宜家衣架真香",
    content:
      "在당근同城收到宜家衣架一组，比新品店便宜一半。卖家就在新村，面交5分钟搞定。图是挂完衣服的样子，稳。",
    author: "新村租客",
    location: "新村",
    distance: "350m",
    likes: 134,
    category: "二手",
    nearby: true,
    topicKeywords: ["宜家", "衣架", "당근", "新村", "面交"],
    allowedImageKeywords: ["clothes", "wardrobe", "hanger", "fashion"],
    forbiddenImageKeywords: ["europe", "food", "landscape"],
    imageSearchQuery: "clothes hanger wardrobe",
    imageCount: 2,
    curatedImages: [
      pexelsPhoto(1926765, "clothes rack"),
      pexelsPhoto(996329, "clothing store"),
    ],
  },
  {
    seedId: 74,
    title: "新村당근找搬家帮手 有偿面聊",
    content:
      "당근上发的求助帖：两个箱子+一个登机箱，新村3楼无电梯。时间周六下午，有偿，图是行李大概体量。",
    author: "搬家求助",
    location: "新村",
    distance: "100m",
    likes: 42,
    category: "求助",
    nearby: true,
    topicKeywords: ["搬家", "당근", "新村", "有偿", "行李"],
    allowedImageKeywords: ["moving", "boxes", "luggage", "suitcase"],
    forbiddenImageKeywords: ["europe", "food", "landscape"],
    imageSearchQuery: "moving boxes luggage",
    imageCount: 2,
    curatedImages: [
      pexelsPhoto(424614, "luggage boxes"),
      pexelsPhoto(912050, "travel luggage"),
    ],
  },
  {
    seedId: 75,
    title: "江南당근出Kindle 几乎全新",
    content:
      "Kindle Paperwhite 出掉，당근面交。屏幕无划痕，带原装线。江南站附近咖啡厅面交，图是开机实拍。",
    author: "阅读爱好者",
    location: "江南站",
    distance: "800m",
    likes: 178,
    category: "二手",
    nearby: true,
    topicKeywords: ["Kindle", "당근", "江南", "面交", "二手"],
    allowedImageKeywords: ["ebook", "tablet", "reading", "kindle"],
    forbiddenImageKeywords: ["europe", "food", "landscape"],
    imageSearchQuery: "ebook reader tablet",
    imageCount: 1,
    curatedImages: [pexelsPhoto(133543, "tablet reading")],
  },
  {
    seedId: 76,
    title: "당근面交二手显示器 这些要检查",
    content:
      "在당근买显示器的经验：面交一定要看坏点、接口、支架。图是我面交时在卖家桌面拍的，27寸无暗病。",
    author: "数码面交党",
    location: "建大",
    distance: "1.2km",
    likes: 267,
    category: "攻略",
    topicKeywords: ["당근", "显示器", "面交", "二手", "攻略"],
    allowedImageKeywords: ["monitor", "computer screen", "desk"],
    forbiddenImageKeywords: ["europe", "food", "landscape"],
    imageSearchQuery: "computer monitor desk",
    imageCount: 2,
    curatedImages: [
      pexelsPhoto(777001, "computer monitor"),
      pexelsPhoto(1957478, "desk setup"),
    ],
  },
  {
    seedId: 77,
    title: "당근买二手自行车 我踩过的坑",
    content:
      "同城买的二手自行车，图是试骑前拍的。刹车和变速一定要当场试，당근上别只看价格，胎纹也要看。",
    author: "骑车通勤",
    location: "延世大学",
    distance: "350m",
    likes: 198,
    category: "攻略",
    nearby: true,
    topicKeywords: ["自行车", "당근", "二手", "避坑", "攻略"],
    allowedImageKeywords: ["bicycle", "bike", "cycling"],
    forbiddenImageKeywords: ["europe", "food", "landscape"],
    imageSearchQuery: "bicycle city commute",
    imageCount: 2,
    curatedImages: [
      pexelsPhoto(248547, "bicycle"),
      pexelsPhoto(2803158, "cycling outdoor"),
    ],
  },
  {
    seedId: 78,
    title: "弘大당근出闲置电饭煲 自取",
    content:
      "单人电饭煲，당근弘大同城。内胆涂层完好，就煮过饭。1.5万自取，图是刚洗完的内胆。",
    author: "小厨房",
    location: "弘大",
    distance: "350m",
    likes: 73,
    category: "二手",
    nearby: true,
    topicKeywords: ["电饭煲", "당근", "弘大", "闲置", "二手"],
    allowedImageKeywords: ["rice cooker", "kitchen", "appliance"],
    forbiddenImageKeywords: ["europe", "landscape", "phone"],
    imageSearchQuery: "kitchen appliance cooking",
    imageCount: 1,
    curatedImages: [pexelsPhoto(2724749, "kitchen appliance")],
  },
  {
    seedId: 79,
    title: "당근约小区咖啡桌 5千拿走",
    content:
      "搬家出小圆桌，당근上约在同小区楼下交易。桌面轻微使用痕，腿稳。图就是现拍，5千韩币。",
    author: "小区出清",
    location: "高丽大",
    distance: "350m",
    likes: 61,
    category: "二手",
    nearby: true,
    topicKeywords: ["咖啡桌", "당근", "小区", "面交", "二手"],
    allowedImageKeywords: ["table", "furniture", "desk", "coffee table"],
    forbiddenImageKeywords: ["europe", "food", "landscape"],
    imageSearchQuery: "small table furniture room",
    imageCount: 2,
    curatedImages: [
      pexelsPhoto(1957478, "small table desk"),
      pexelsPhoto(1571460, "apartment interior"),
    ],
  },
  {
    seedId: 80,
    title: "建大당근出一套专业课教材",
    content:
      "几本专业书一起出，당근建大面交。无乱涂，有少量笔记。图是堆在一起拍的，整套5万可议。",
    author: "建大学长",
    location: "建大",
    distance: "100m",
    likes: 112,
    category: "二手",
    nearby: true,
    topicKeywords: ["教材", "당근", "建大", "专业课", "二手"],
    allowedImageKeywords: ["books", "textbook", "study", "reading"],
    forbiddenImageKeywords: ["europe", "food", "landscape"],
    imageSearchQuery: "textbooks study books",
    imageCount: 2,
    curatedImages: [
      pexelsPhoto(207662, "study books"),
      pexelsPhoto(7688336, "books desk"),
    ],
  },
];
