import { pexelsPhoto } from "./pexels-url";
import type { AutoPostTemplate } from "./types";

/** Batch 5 (81–90): 韩式美食小红书/INS风格 — 原创中文探店帖，非抓取转载。 */
export const AUTO_POST_TEMPLATES_J: AutoPostTemplate[] = [
  {
    seedId: 81,
    title: "建大后端烤五花 这盘肉我先冲",
    content:
      "周五下课后和同学来后端吃烤五花，图就是上烤盘那刻。厚切五花配蒜片，人均2.5万，记得早点去不然排队。",
    author: "烤肉打卡",
    location: "建大",
    distance: "100m",
    likes: 1247,
    category: "探店",
    nearby: true,
    following: true,
    imageFirst: true,
    requireImages: true,
    topicKeywords: ["烤五花", "建大", "烤肉", "探店", "美食"],
    allowedImageKeywords: ["korean bbq", "grill", "meat", "bbq"],
    forbiddenImageKeywords: ["europe", "landscape", "bedroom"],
    imageSearchQuery: "korean bbq grill meat",
    imageCount: 2,
    curatedImages: [
      pexelsPhoto(6660060, "korean bbq grill"),
      pexelsPhoto(1267320, "grilled meat"),
    ],
  },
  {
    seedId: 82,
    title: "弘大贝果早餐 拍照5分钟吃完3分钟",
    content:
      "弘大这家贝果店，图是刚出炉拿铁+贝果。外脆内软，奶油芝士款推荐。周末10点后人多，建议开门就去。",
    author: "早餐探店",
    location: "弘大",
    distance: "350m",
    likes: 892,
    category: "探店",
    nearby: true,
    following: true,
    topicKeywords: ["贝果", "早餐", "弘大", "咖啡", "探店"],
    allowedImageKeywords: ["bagel", "breakfast", "brunch", "cafe"],
    forbiddenImageKeywords: ["europe", "landscape", "monitor"],
    imageSearchQuery: "bagel breakfast cafe",
    imageCount: 2,
    curatedImages: [
      pexelsPhoto(1640777, "brunch breakfast"),
      pexelsPhoto(376464, "cafe latte"),
    ],
  },
  {
    seedId: 83,
    title: "明洞炸鸡配生啤 周五固定节目",
    content:
      "明洞这家炸鸡，图是刚上桌的酱油+甜辣双拼。皮很脆，啤酒必须加冰。人均1.8万左右，适合下课后。",
    author: "炸鸡啤酒",
    location: "明洞",
    distance: "100m",
    likes: 1567,
    category: "探店",
    nearby: true,
    topicKeywords: ["炸鸡", "啤酒", "明洞", "周五", "美食"],
    allowedImageKeywords: ["fried chicken", "chicken", "korean food"],
    forbiddenImageKeywords: ["europe", "landscape", "bedroom"],
    imageSearchQuery: "fried chicken korean food",
    imageCount: 2,
    curatedImages: [
      pexelsPhoto(1267320, "korean fried food"),
      pexelsPhoto(725997, "restaurant meal"),
    ],
  },
  {
    seedId: 84,
    title: "新村血肠汤 宿醉第二天救我",
    content:
      "宿醉第二天来新村喝血肠汤，图就是上桌那碗。汤头很浓，配米饭绝配。早上8点去不用等位。",
    author: "解酒汤达人",
    location: "新村",
    distance: "100m",
    likes: 634,
    category: "探店",
    nearby: true,
    topicKeywords: ["血肠汤", "新村", "韩餐", "解酒", "美食"],
    allowedImageKeywords: ["korean soup", "korean food", "meal", "bowl"],
    forbiddenImageKeywords: ["europe", "landscape", "phone"],
    imageSearchQuery: "korean soup food bowl",
    imageCount: 1,
    curatedImages: [pexelsPhoto(1835928, "korean soup bowl")],
  },
  {
    seedId: 85,
    title: "海云台生鱼片 鲜到没话说",
    content:
      "釜山海云台市场买的生鱼片，图是老板切完摆盘。蘸酱油+wasabi，人均3-4万。早上去最新鲜。",
    author: "釜山吃货",
    location: "海云台",
    distance: "1.2km",
    likes: 1123,
    category: "探店",
    topicKeywords: ["生鱼片", "海云台", "釜山", "海鲜", "美食"],
    allowedImageKeywords: ["seafood", "sashimi", "fish", "korean food"],
    forbiddenImageKeywords: ["europe", "landscape", "bedroom"],
    imageSearchQuery: "seafood sashimi plate",
    imageCount: 2,
    curatedImages: [
      pexelsPhoto(842571, "seafood plate"),
      pexelsPhoto(725997, "seafood dining"),
    ],
  },
  {
    seedId: 86,
    title: "梨泰院Brunch摆盘 真的出片",
    content:
      "梨泰院Brunch店，图是班尼迪克+沙拉那盘。光线下午2点最好，靠窗位要预约。人均2.5-3万。",
    author: "brunch拍照",
    location: "梨泰院",
    distance: "1.2km",
    likes: 978,
    category: "探店",
    following: true,
    topicKeywords: ["Brunch", "梨泰院", "摆盘", "探店", "美食"],
    allowedImageKeywords: ["brunch", "breakfast", "meal", "restaurant"],
    forbiddenImageKeywords: ["europe", "landscape", "monitor"],
    imageSearchQuery: "brunch plate restaurant",
    imageCount: 2,
    curatedImages: [
      pexelsPhoto(1640777, "brunch plate"),
      pexelsPhoto(376464, "brunch cafe"),
    ],
  },
  {
    seedId: 87,
    title: "汉江便利店饭团野餐 人均5千",
    content:
      "汉江野餐没做饭，便利店买三角饭团+饮料，图是铺毯子那刻。春秋季风大带外套，垃圾记得带走。",
    author: "汉江野餐",
    location: "汝矣岛",
    distance: "2.4km",
    likes: 756,
    category: "探店",
    nearby: true,
    topicKeywords: ["汉江", "饭团", "野餐", "便利店", "美食"],
    allowedImageKeywords: ["picnic", "snack", "food", "outdoor meal"],
    forbiddenImageKeywords: ["europe", "bedroom", "monitor"],
    imageSearchQuery: "picnic food outdoor",
    imageCount: 2,
    curatedImages: [
      pexelsPhoto(1071882, "snack food"),
      pexelsPhoto(7625056, "convenience store snack"),
    ],
  },
  {
    seedId: 88,
    title: "建大中国街麻辣香锅 重口党狂喜",
    content:
      "建大中国街麻辣香锅，图是刚出锅那盆。可以选微辣到中辣，加宽粉+午餐肉。人均1.5-2万，中文点单。",
    author: "麻辣香锅控",
    location: "建大",
    distance: "350m",
    likes: 1034,
    category: "探店",
    nearby: true,
    following: true,
    topicKeywords: ["麻辣香锅", "建大", "中国街", "中餐", "美食"],
    allowedImageKeywords: ["hot pot", "chinese food", "spicy food", "meal"],
    forbiddenImageKeywords: ["europe", "landscape", "bedroom"],
    imageSearchQuery: "chinese hot pot spicy",
    imageCount: 2,
    curatedImages: [
      pexelsPhoto(699953, "chinese hot pot"),
      pexelsPhoto(958545, "chinese food"),
    ],
  },
  {
    seedId: 89,
    title: "江南站抹茶拿铁 苦甜刚好",
    content:
      "江南站后面抹茶专门店，图是热抹茶拿铁。不是齁甜那种，抹茶味挺正。适合写论文前来一杯。",
    author: "抹茶脑袋",
    location: "江南站",
    distance: "100m",
    likes: 567,
    category: "探店",
    nearby: true,
    topicKeywords: ["抹茶", "拿铁", "江南", "咖啡", "探店"],
    allowedImageKeywords: ["matcha", "latte", "green tea", "cafe drink"],
    forbiddenImageKeywords: ["europe", "landscape", "phone"],
    imageSearchQuery: "matcha latte cafe",
    imageCount: 1,
    curatedImages: [pexelsPhoto(376464, "matcha latte cafe")],
  },
  {
    seedId: 90,
    title: "广藏市场绿豆饼 刚出锅烫手",
    content:
      "广藏市场绿豆饼，图是刚出锅那袋。外酥里糯，1千一个别买贵。周末排队20分钟正常。",
    author: "市场小吃",
    location: "钟路",
    distance: "3.8km",
    likes: 889,
    category: "探店",
    topicKeywords: ["绿豆饼", "广藏市场", "小吃", "探店", "美食"],
    allowedImageKeywords: ["street food", "korean snack", "market food"],
    forbiddenImageKeywords: ["europe", "bedroom", "monitor"],
    imageSearchQuery: "korean street food market",
    imageCount: 2,
    curatedImages: [
      pexelsPhoto(7319149, "korean street food"),
      pexelsPhoto(2313686, "market food stall"),
    ],
  },
];
